---

- hosts: all
  become: true
  tasks:

  - name: install httpd package
    yum:
      name: httpd
      state: latest

  - name: add php support for apache
    yum:
      name: php
      state: latest
