---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "8.2" 

  - name: install httpd package
    yum:
      name: httpd
      state: latest

  - name: add php support for apache
    yum:
      name: php
      state: latest
