---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "8.2" 

  - name: install httpd and php package
    package:          
      name: 
        - httpd
        - php
      state: latest

