---

- hosts: all
  become: true
  pre_tasks:
  
  - name: install updates (CentOS)
    tags: always
    package:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "8.2" 

  - name: install httpd and php package 
    tags: apache,centos,httpd     
    package:    
      name: 
        - httpd
        - php
      state: latest

- hosts: db_servers
  become: true
  tasks:
  
  - name: install mariadb package
    tags: centos,db,mariadb
    package: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:
    
  - name: install samba package
    tags: samba
    package: 
      name: samba
      state: latest
