---

- hosts: all
  become: true
  pre_tasks:
  
  - name: update repo cache (CentOS)
    tags: always
    package:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  tasks:
 
#  - name: create simone user
#    tags: always
#    user:
#      name: simone
#      groups: root
 
  - name: add ssh key for simone
    tags: always
    authorized_key: 
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILZVyJBB3N0vxr++nZ7eAHyYOGj4TH8KFF2jmdq8+qN8 ansible"
 
#  - name: add sudoers file for simone
#    tags: always
#    copy:
#      src: sudoer_simone
#      dest: /etc/sudoers.d/simone
#      owner: root
#      group: root
#      mode: 0440


- hosts: workstation
  become: true
  tasks:
    
    - name: install unzip
      package: 
       name: unzip
    
    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root


- hosts: web_servers
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "8.2" 

  - name: install httpd and php package 
    tags: apache,centos,httpd     
    package:    
      name: 
        - httpd
        - php
      state: latest

  - name: starting httpd
    tags: apache,centos,httpd
    service: 
      name: httpd
      state: started
      enabled: yes
 
  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin niksa.car2000@gmail.com
    register: httpd

  - name: restart httpd
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: apache,httpd 
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 

- hosts: db_servers
  become: true
  tasks:
  
  - name: install mariadb package
    tags: centos,db,mariadb
    package: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:
    
  - name: install samba package
    tags: samba
    package: 
      name: samba
      state: latest
